name: acl-ssl
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=9.10.1.4=haad7af6_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libcudnn=9.10.1.4=h7d33bf5_0
  - libcudnn-dev=9.10.1.4=h0fdc2d1_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - absl-py==2.3.1
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - cmake==4.1.2
      - filelock==3.20.0
      - fsspec==2025.10.0
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - lit==18.1.8
      - markdown==3.10
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.24.1
      - oauthlib==3.3.1
      - opencv-python==4.7.0.72
      - packaging==25.0
      - pillow==12.0.0
      - protobuf==3.20.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.2.2
      - scipy==1.15.3
      - six==1.16.0
      - sympy==1.14.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.6.0
      - tokenizers==0.13.3
      - torch==2.0.0+cu118
      - torchaudio==2.0.0+cu118
      - torchvision==0.15.0+cu118
      - tqdm==4.65.0
      - transformers==4.25.1
      - triton==2.0.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
